#配置数据源信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
server:
  port: 9000

logging:
  file:
    name: ./project.log
  level:
    com:
      qy25:
        cn:
          mapper: debug